# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - webapp-ecomm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore Packages
        run: dotnet restore eShopOnWeb.sln

      - name: Build Solution
        run: dotnet build eShopOnWeb.sln --configuration Release --no-restore

      - name: Publish Application
        run: dotnet publish src/Web/Web.csproj -c Release -o publish --no-build

      - name: Verify Publish Output
        run: |
          echo "Publishing files..."
          dir publish
          dir publish /s

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-package
          path: publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp-package
          path: publish

      - name: Verify Downloaded Files
        run: |
          echo "Downloaded files..."
          dir publish
          dir publish /s

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: webapp-advance
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
